### ISSUE TITLE
[RFE] Migrate Repos

### ISSUE THREAD

**Issue by christianh814** [redhat-gpte-devopsautomation/gitea-operator#10]
Add the ability to migrate over repos to use. Defaults noted in comments

```yaml
giteaMigrateRepos:
  - name: "myapp"
    repo: https://github.com/wolfgang/servus-app
    description: "This is a greeting app" # default is empty string
    issues: false #migrate issues? - default is false
    milestones: false #migrate milestones? - default is false
    mirror: false #create mirror? - default false
    private: false #private or public? - default is false
    owner: "user1" #which account to migrate this to? - default is the admin user
  - name: "anotherapp"
    repo: https://github.com/wolfgang/tschuss-app
    description: "This is an app that says goodbye"
    owner: "user2"
```

Right now I'm doing this via a post sync hook, and would like to avoid using `curl` for all of this :)
