### ISSUE TITLE
SSH server capabilities not implemented

### ISSUE THREAD

**Issue by websecwrc** [redhat-gpte-devopsautomation/gitea-operator#32]
The documentation references:
```
giteaSshPort:
  description: 'Port for Gitea to start an SSH server on. Default: 2022'
  type: integer
giteaDisableSsh:
  description: 'Disable SSH for Gitea. Default: true'
  type: boolean
giteaStartSshServer:
  description: 'Start SSH Server in the Gitea container. Default: false'
```

... however there is no plumbing at all for making this happen.

There are these defaults:
```
_gitea_ssh_port: 2022
_gitea_disable_ssh: false
_gitea_start_ssh_server: true
```

There should be `{% if _gitea_disable_ssh == false && _gitea_start_ssh_server == true %}` conditionals implemented for these in https://github.com/rhpds/gitea-operator/tree/31e280b7629ef969d04a5bb8f42a64d92c76facb/roles/gitea-ocp/templates so it doesn't confuse the user into thinking these are available.
