### ISSUE TITLE
[RFE] Add the ability to create users

### ISSUE THREAD

**Issue by christianh814** [redhat-gpte-devopsautomation/gitea-operator#9]
It would be cool to be able to add users declaratively, using this Operator. For example:

```yaml
giteaCreateUsers:
  - name: "user1"
    password: "myPassowrd"
    email: "user1@example.com"
    changePassword: false
    sendNotification: false
  - name: "user2"
    generatePassword: true
    email: "user2@example.com"
    changePassword: true
    sendNotification: true
```

Right now, I'm doing this as a "post sync hook" in my workflow and want to switch off using `curl` and have the operator take care of it for me :)
